# Generated by Django 4.2.17 on 2025-01-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/profile/avatar/', verbose_name='Avatar')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('marriage', models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=1, null=True, verbose_name='Marriage')),
                ('education', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('skype', 'Skype'), ('github', 'GitHub'), ('pinterest', 'Pinterest'), ('snapchat-ghost', 'Snapchat'), ('reddit', 'Reddit'), ('google', 'Google')], max_length=15, null=True, verbose_name='Application Name')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='users/profile/SocialMediaQRCode/', verbose_name='QR Code')),
                ('link', models.CharField(blank=True, max_length=400, null=True, verbose_name='Link')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'User Social Media Profile',
                'verbose_name_plural': 'User Social Media Profiles',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Iran', max_length=30, null=True, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('main_st', models.CharField(blank=True, max_length=30, null=True, verbose_name='Main Street')),
                ('auxiliary_st', models.CharField(blank=True, max_length=30, null=True, verbose_name='Auxiliary Street')),
                ('street_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Building Number')),
                ('building_unit_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Building Unit Number')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
    ]
