# Generated by Django 4.2.17 on 2024-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_title",
                    models.CharField(
                        help_text="فقط برای نمایش در جداول دیتابیس. عنوان اصلی در بخش عنوان بخشها می باشد",
                        max_length=200,
                        verbose_name="عنوان انگلیسی",
                    ),
                ),
                (
                    "fa_title",
                    models.CharField(
                        help_text="فقط برای نمایش در جداول دیتابیس. عنوان اصلی در بخش عنوان بخشها می باشد",
                        max_length=200,
                        verbose_name="عنوان فارسی",
                    ),
                ),
                (
                    "en_description",
                    models.TextField(verbose_name="متن انگلیسی درباره ما"),
                ),
                (
                    "fa_description",
                    models.TextField(verbose_name="متن فارسی درباره ما"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
        migrations.CreateModel(
            name="PhotoSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_title",
                    models.CharField(
                        max_length=100, verbose_name="عنوان انگلیسی اسلاید"
                    ),
                ),
                (
                    "fa_title",
                    models.CharField(max_length=100, verbose_name="عنوان فارسی اسلاید"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="برای نمایش در پس زمینه اسلاید استفاده می شود.",
                        upload_to="slider/",
                        verbose_name="تصور اسلاید",
                    ),
                ),
                ("en_text", models.TextField(verbose_name="متن انگلیسی اسلاید")),
                ("fa_text", models.TextField(verbose_name="متن فارسی اسلاید")),
                (
                    "order",
                    models.SmallIntegerField(
                        help_text="ترتیب نمایش اسلاید را مشخص کنید که چندمین اسلاید باشد.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلاید ها",
            },
        ),
    ]
