# Generated by Django 4.2.17 on 2024-12-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strat_work_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت شروع کار"
                    ),
                ),
                (
                    "end_work_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت پایان کار"
                    ),
                ),
                (
                    "start_work_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "شنبه"),
                            ("2", "یک شنبه"),
                            ("3", "دوشنبه"),
                            ("4", "سه شنبه"),
                            ("5", "چهار شنبه"),
                            ("6", "پنج شنبه"),
                            ("7", "جمعه"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="اولین روز کاری در هفته",
                    ),
                ),
                (
                    "end_work_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "شنبه"),
                            ("2", "یک شنبه"),
                            ("3", "دوشنبه"),
                            ("4", "سه شنبه"),
                            ("5", "چهار شنبه"),
                            ("6", "پنج شنبه"),
                            ("7", "جمعه"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="آخرین روز کاری در هفته",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="انتخاب مالک سایت از بین کاربران برای نمایش اطلاعات تماس.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "مالک سایت",
                "verbose_name_plural": "مالک سایت",
            },
        ),
    ]
