# Generated by Django 4.2.17 on 2024-12-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="websiteowner",
            options={
                "verbose_name": "WebsiteOwner",
                "verbose_name_plural": "WebsiteOwner",
            },
        ),
    ]
