# Generated by Django 4.2.17 on 2025-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_websiteowner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, help_text='نامی که در بالای صفحه به عنوان تایتل نمایش داده می شود.', max_length=100, verbose_name='عنوان سایت')),
                ('main_title', models.CharField(blank=True, help_text='نامی که به عنوان اسم اصلی سایت و یا به عنوان لوگوی سایت استفاده می شود.', max_length=200, verbose_name='نام سایت')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='website/images/logo/', verbose_name='تصویر لوگو')),
                ('logo_touch_icon', models.ImageField(blank=True, null=True, upload_to='website/images/logo/', verbose_name='تصویر آیکون لوگو')),
                ('description', models.CharField(blank=True, help_text='توضیح مختصری راجع به اهداف سایت', max_length=400, verbose_name='شرح سایت')),
                ('seo_keyword', models.CharField(blank=True, help_text='کلمات کلیدی برای کمک به موتور جستجوگر گوگل', max_length=400, verbose_name='کلمات کلیدی برای سئو')),
            ],
            options={
                'verbose_name': 'مشخصات وب سایت',
                'verbose_name_plural': 'مشخصات وب سایت',
            },
        ),
    ]
