# Generated by Django 4.2.17 on 2025-01-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_websitedetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitedetails',
            options={'verbose_name': 'Website Details', 'verbose_name_plural': 'Website Details'},
        ),
    ]
