# Generated by Django 4.2.17 on 2025-01-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0005_alter_websitedetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteowner',
            options={'verbose_name': 'Website Owner', 'verbose_name_plural': 'Website Owner'},
        ),
        migrations.AddField(
            model_name='websitedetails',
            name='main_title_en',
            field=models.CharField(blank=True, help_text='The name that is used as the main name of the site or as the site logo.', max_length=200, verbose_name='English Main Title'),
        ),
        migrations.AddField(
            model_name='websitedetails',
            name='page_title_en',
            field=models.CharField(blank=True, help_text='The name that appears at the top of the page as the title.', max_length=100, verbose_name='English Page Title'),
        ),
        migrations.AlterField(
            model_name='websiteowner',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Website Owner'),
        ),
    ]
