# Generated by Django 4.2.17 on 2025-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_alter_websiteowner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=10, unique=True, verbose_name='Section Name')),
                ('en_title', models.CharField(max_length=50, verbose_name='English Title')),
                ('fa_title', models.CharField(max_length=50, verbose_name='Persian Title')),
                ('en_subtitle', models.CharField(blank=True, max_length=400, verbose_name='English Subtitle')),
                ('fa_subtitle', models.CharField(blank=True, max_length=400, verbose_name='Persian Subtitle')),
            ],
            options={
                'verbose_name': 'Titles',
                'verbose_name_plural': 'Titles',
            },
        ),
    ]
